name: Auto Post Macau Result

on:
  schedule:
    - cron: '0 6 * * *'   # 13:00 WIB
    - cron: '0 9 * * *'   # 16:00 WIB
    - cron: '0 12 * * *'  # 19:00 WIB
    - cron: '0 15 * * *'  # 22:00 WIB
    - cron: '0 17 * * *'  # 00:00 WIB
  workflow_dispatch:

jobs:
  auto-post-macau:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Macau result script
        env:
          WP_USER: ${{ secrets.WP_USER }}
          WP_PASS: ${{ secrets.WP_PASS }}
          WP_API_URL: ${{ secrets.WP_API_URL }}
        run: |
          python run.py
