name: Auto Post Macau Result

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  auto-post-macau:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install chromium

      - name: Jalankan Script Macau
        env:
          WP_USER: ${{ secrets.WP_USER }}
          WP_PASS: ${{ secrets.WP_PASS }}
          WP_API_URL: ${{ secrets.WP_API_URL }}
        run: |
          python run.py
